apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga-service
  namespace: kong
spec:
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  selector:
    app: konga