apiVersion: v1
kind: Secret
metadata:
  name: kong-migration-secret
  namespace: kong
type: Opaque
data:
  kong-database: "cG9zdGdyZXM=" #postgres
  kong-pg-database: "a29uZw==" #kong
  kong-pg-host: "a29uZy1kYg==" #kong-db
  kong-pg-user: "cG9zdGdyZXM=" #postgres
  kong-pg-password: "a29uZw==" #kong
