apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_ADAPTER
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database-adapter
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database-password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: database-port
        - name: KONGA_HOOK_TIMEOUT
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: konga-hook-timeout
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: node-env
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: konga-secret
              key: token-secret
        ports:
        - containerPort: 1337
          protocol: TCP
