apiVersion: v1
kind: Service
metadata:
  name: kong-database
spec:
  #clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  #selector:
    #app: postgresql-db
    #clusterIP: None